name        'puppetlabs-erlang'
version     '1.0.0'
source      'git://github.com/puppetlabs/puppetlabs-erlang.git'
author      'Puppet Labs'
summary     'Module for installing erlang'
description 'Module to set up the repo and install erlang'
license     'Apache License, Version 2.0'
dependency  'puppetlabs/apt'
dependency  'puppetlabs/stdlib'
